#!/usr/bin/env bash
# A script that displays information about subdomains
fetch() {
  dig "$2.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk -v domain="$2" '{print "The subdomain " domain " is a " $7 " record and points to " $8}'
}

if [ "$#" -eq 1 ]
then
  for subdomain in "www" "lb-01" "web-01" "web-02"
  do
    fetch "$1" "$subdomain"
  done
else
  fetch "$1" "$2"
fi
