#!/usr/bin/env bash
# A script that transfers the a file from our client to a server

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";

elif [ $# -eq 3 ]; then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/";
else
    # scp file.txt remote_username@10.10.0.2:/remote/directory
    scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/" "$4";
fi
