#!/usr/bin/env bash
# A script that configures a new Ubuntu machine to respect some requirements
agt-get update && apt-get install -y nginx;
sudo rm /usr/local/etc/nginx/nginx.conf;
sudo touch /usr/local/etc/nginx/nginx.conf;

nginx_config="/usr/local/etc/nginx/nginx.conf";

cat "\
http {
  server {
    listen 80;
    root /;
  }
}" > ${nginx_config};

touch /index.html
cat "\
<!DOCTYPE HTML>
<html>
<head>
	<meta charset=\"utf-8\">
	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
	<title>BOXES</title>
</head>
<body>
  <h1>Hello World!<\h1>
</body>
</html>
" > ~/index.html;
nginx -s reload
