#!/usr/bin/env bash
# A bash script to configure a new Ubuntu machine given certain requirements
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt -y install nginx
sudo service nginx stop
echo "Hello World!" > ./index.nginx-debian.html
sudo mv ./index.nginx-debian.html /var/www/html/
sudo service nginx start
sudo ufw allow 'Nginx Full'
