#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
sudo apt -y update
sudo apt -y install nginx
sudo service nginx stop
echo "Hello World!" > ./index.nginx-debian.html
sudo mv ./index.nginx-debian.html /var/www/html/
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\www.youtube.com/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
sudo service nginx start
sudo ufw allow 'Nginx Full'
