#!/usr/bin/env bash
# A bash script to configure a new Ubuntu machine given certain requirements
sudo apt-get -y update
sudo apt -y install nginx

echo "Hello World!" > ./index.nginx-debian.html
sudo mv ./index.nginx-debian.html /var/www/html/
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/google.com permanent;\n\tadd_header X-Served-By $(hostname);/" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > ./custom_404.html
sudo mv ./custom_404.html /usr/share/nginx/html/
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/google.com permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default

sudo service nginx restart
sudo ufw allow 'Nginx Full'
