#!/usr/bin/env bash
# Manages the "manage_my_process" daemon

pos_arg=$1

if [ "$pos_arg" = "start" ]; then
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$pos_arg" = "stop" ]; then
	cat /var/run/my_process.pid | head -1 | xargs kill -KILL
	rm -rf /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$pos_arg" = "restart" ]; then
	pkill -f manage_my_process
	rm -rf /var/run/my_process.pid
	./manage_my_process
	echo $! > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
