#!/usr/bin/env bash
# A script that displays "To infinity and beyond" indefinitely
#	- in between each iteration of the loop, sleep process for 2 seconds

i=1
while [ $i -eq 1 ]; do
	echo "To infinity and beyond"
	sleep 2
done
