#!/usr/bin/env bash
# A script that displays "To infinity and beyond" indefinitely
#	- in between each iteration of the loop, sleep process for 2 seconds

while true; do
	echo "To infinity and beyond"
	sleep 2
done
