#!/usr/bin/env bash
# A bash script that displays "To infinity and beyond" indefinitely,
#	- sleeps for two seconds with every iteration

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
