#!/usr/bin/env bash
# Displays number from 1 to 100
#	- display "FizzBuzz" when the number is a multiple '3' or '5'
#	- display "Fizz" when the number is a multiple of "3"
#	- display "Buzz" when the number is a multiple of "5"

i=1
while [ $i -le 100 ]; do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((i%3)) -eq 0 ]; then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]; then
		echo "Buzz"
	else
		echo $i
	fi
	i=$((i + 1))
done