#!/usr/bin/env bash
# A Bash script that displays the contents of the current directory in a list
# format, where only the part of the name after the first dash is displayed

dir_contents=ls

echo $dir_contents
